#!/usr/bin/env zsh

export EDITOR=nvim

alias tm="~/.config/zsh/tm.sh"

alias resource="source ~/.zshrc"

alias r="R --no-save"
alias R="R --no-save"
alias Rtest="Rscript -e 'devtools::test()'"
alias Rcheck="R CMD check ."

alias vi="nvim"
alias vim="nvim"

export LANG="en_US.UTF-8"
